### ISSUE TITLE
RPIcam compatibility

### ISSUE THREAD

**Issue by Astro-Otter-Space** [GuLinux/AstroPhoto-Plus-Desktop#13]
Hi, i've just a little question, is your apllication running with RPI camera v2 ?
Thank you.

**Comment by GuLinux** [comment]
Hi,
kind of.
AstroPhoto Plus doesn't support hardware _directly_, it relies on INDI for hardware support.
I think Raspberry Pi camera should be supported via the INDI V4L2 driver.
I'm closing this as it's not really relevant to AstroPhoto Plus, if you have specific hardware issues you can use the INDI forum and support.

(It is also kinda the wrong project anyway, as this is just the desktop wrapper, not the "real" application)

**Comment by Astro-Otter-Space** [comment]
Thank you for your answer :)
I'm trying to use indi_rpicam (the driver for raspi cam) in INDI/Ekos but it doesn't work. I've create an issue in indi 3rd party drivers github yet. However i will test your application, it looks great.
